rbacEnable: true
namePrefix: kp
externalEnable: false
image:
  repository: ceph/ceph:v14.2.6
cephAllowUnsupported: false
skipUpgradeChecks: false
continueUpgradeAfterChecksEvenIfNotHealthy: false
allowMultiplePerNode: false
dataDirHostPath: /var/lib/rook-kp
monCount: 2
dasbboardEnabled: false
dasbboardSSL: true
monitoringEnabled: false
hostNetwork: false
rbdMirroring:
  workers: 0
crashCollector:
  disable: false
placement:
  all: false
useAllNodes: false
useAllDevices: false
Release:
  Namespace: rook-ceph-kp
nodes:
  - name: lenlmsdev24
    devices:
      - sdg
      - sdh
